# Generated by Django 2.2.28 on 2025-10-02 22:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TceArquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='tce/arquivos/%Y/%m/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('nome_sugerido', models.CharField(blank=True, max_length=255, verbose_name='Nome Sugerido (Padrão TCE)')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('xml', 'XML')], max_length=10, verbose_name='Tipo')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('tamanho_mb', models.FloatField(default=0, verbose_name='Tamanho (MB)')),
                ('tamanho_ok', models.BooleanField(default=False, verbose_name='Tamanho ≤ 5MB')),
                ('arquivo_reduzido', models.FileField(blank=True, null=True, upload_to='tce/reduzidos/%Y/%m/', verbose_name='Arquivo Reduzido')),
                ('tamanho_reduzido_mb', models.FloatField(blank=True, null=True, verbose_name='Tamanho Reduzido (MB)')),
                ('ocr_aplicado', models.BooleanField(default=False, verbose_name='OCR Aplicado')),
                ('ocr_ok', models.BooleanField(default=False, verbose_name='OCR OK (Pesquisável)')),
                ('arquivo_ocr', models.FileField(blank=True, null=True, upload_to='tce/ocr/%Y/%m/', verbose_name='Arquivo com OCR')),
                ('assinado', models.BooleanField(default=False, verbose_name='Assinado')),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to='tce/assinados/%Y/%m/', verbose_name='Arquivo Assinado')),
                ('certificado_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Informações do Certificado')),
                ('p7s_gerado', models.BooleanField(default=False, verbose_name='.p7s Gerado')),
                ('arquivo_p7s', models.FileField(blank=True, null=True, upload_to='tce/p7s/%Y/%m/', verbose_name='Arquivo .p7s')),
                ('hash_sha256', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado (Pronto para Envio)')),
                ('metadados', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_tce_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo TCE',
                'verbose_name_plural': 'Arquivos TCE',
                'ordering': ['pasta', 'nome_original'],
            },
        ),
        migrations.CreateModel(
            name='TceProcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Processo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ano', models.IntegerField(default=2025, verbose_name='Ano')),
                ('periodo', models.CharField(blank=True, help_text='Ex: 3º Quadrimestre, Anual, Mensal', max_length=100, verbose_name='Período')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_preparacao', 'Em Preparação'), ('validado', 'Validado'), ('enviado', 'Enviado ao TCE'), ('devolvido', 'Devolvido pelo TCE'), ('aprovado', 'Aprovado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('numero_protocolo', models.CharField(blank=True, max_length=100, verbose_name='Número de Protocolo TCE')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('recibo_tce', models.TextField(blank=True, verbose_name='Recibo TCE')),
                ('hash_envio', models.CharField(blank=True, max_length=64, verbose_name='Hash do Envio')),
                ('metadados', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_tce_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo TCE',
                'verbose_name_plural': 'Processos TCE',
                'ordering': ['-ano', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TcePasta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Pasta')),
                ('categoria', models.CharField(choices=[('financeiro', 'Financeiro - Gestão Orçamentária'), ('administrativo', 'Administrativo - Gestão Administrativa'), ('legislativo', 'Legislativo - Gestão Legislativa'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='tce.TceProcesso')),
            ],
            options={
                'verbose_name': 'Pasta TCE',
                'verbose_name_plural': 'Pastas TCE',
                'ordering': ['processo', 'ordem', 'nome'],
                'unique_together': {('processo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='TceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('processo_criado', 'Processo Criado'), ('pasta_criada', 'Pasta Criada'), ('arquivo_upload', 'Upload de Arquivo'), ('arquivo_reduzido', 'Arquivo Reduzido'), ('ocr_aplicado', 'OCR Aplicado'), ('arquivo_assinado', 'Arquivo Assinado'), ('p7s_gerado', 'Arquivo .p7s Gerado'), ('processo_validado', 'Processo Validado'), ('processo_enviado', 'Processo Enviado ao TCE'), ('recibo_recebido', 'Recibo TCE Recebido'), ('erro', 'Erro')], max_length=30, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Dados do Evento')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True, verbose_name='Ocorrido em')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('arquivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tce.TceArquivo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tce.TceProcesso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_tce', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log TCE',
                'verbose_name_plural': 'Logs TCE',
                'ordering': ['-ocorrido_em'],
            },
        ),
        migrations.CreateModel(
            name='TceAssinatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem da Assinatura')),
                ('papel', models.CharField(choices=[('presidente', 'Presidente'), ('ordenador', 'Ordenador de Despesas'), ('contador', 'Contador'), ('controlador', 'Controlador Interno'), ('procurador', 'Procurador'), ('outros', 'Outros')], max_length=20, verbose_name='Papel do Assinante')),
                ('certificado_tipo', models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], max_length=10, verbose_name='Tipo de Certificado')),
                ('certificado_serial', models.CharField(blank=True, max_length=100, verbose_name='Serial do Certificado')),
                ('certificado_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome no Certificado')),
                ('certificado_validade', models.DateField(blank=True, null=True, verbose_name='Validade do Certificado')),
                ('valida', models.BooleanField(default=True, verbose_name='Assinatura Válida')),
                ('cadeia_icp_ok', models.BooleanField(default=False, verbose_name='Cadeia ICP Válida')),
                ('carimbo_tempo', models.BooleanField(default=False, verbose_name='Carimbo de Tempo Presente')),
                ('ltv', models.BooleanField(default=False, verbose_name='LTV (Long Term Validation)')),
                ('hash_assinatura', models.CharField(blank=True, max_length=64, verbose_name='Hash da Assinatura')),
                ('assinado_em', models.DateTimeField(auto_now_add=True, verbose_name='Assinado em')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='tce.TceArquivo')),
                ('assinado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura Digital',
                'verbose_name_plural': 'Assinaturas Digitais',
                'ordering': ['arquivo', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='tcearquivo',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='tce.TcePasta'),
        ),
    ]
