# Generated by Django 2.2.28 on 2026-02-09 11:43

from django.db import migrations, models
import sapl.tce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tce', '0003_tcepasta_subpastas_customizadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tceprocesso',
            name='ano',
            field=models.IntegerField(default=sapl.tce.models.get_current_year, verbose_name='Ano'),
        ),
    ]
