# Generated by Django 2.2 on 2026-01-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('base', '0060_auto_20240812_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo_conteudo', models.CharField(
                    choices=[
                        ('proposicao', 'Proposição'),
                        ('materia', 'Matéria Legislativa'),
                        ('docacessorio', 'Documento Acessório'),
                        ('docadm', 'Documento Administrativo'),
                        ('norma', 'Norma Jurídica'),
                    ],
                    max_length=20,
                    verbose_name='Tipo de Conteúdo',
                    help_text='Tipo de documento ao qual este template se aplica'
                )),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Tipo Específico')),
                ('arquivo', models.FileField(
                    upload_to='templates/',
                    verbose_name='Arquivo do Template',
                    help_text='Arquivo .docx com o template do documento'
                )),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(
                    default=False,
                    verbose_name='Padrão',
                    help_text='Se marcado, será o template padrão para este tipo de conteúdo'
                )),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('content_type', models.ForeignKey(
                    blank=True,
                    help_text='Tipo específico de documento (ex: Projeto de Lei, Requerimento)',
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='contenttypes.ContentType',
                    verbose_name='Tipo Específico'
                )),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'ordering': ['tipo_conteudo', 'nome'],
            },
        ),
    ]
