# Generated by Django 2.2.28 on 2026-02-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_documenttemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfig',
            options={'ordering': ('-id',), 'permissions': (('menu_sistemas', 'Renderizar Menu Sistemas'), ('view_tabelas_auxiliares', 'Visualizar Parâmetros')), 'verbose_name': 'Configurações da Aplicação', 'verbose_name_plural': 'Configurações da Aplicação'},
        ),
        migrations.AlterField(
            model_name='tipoautor',
            name='content_type',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Modelagem no SGVP'),
        ),
    ]
