# Generated by Django 2.2.28 on 2026-02-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_auto_20260209_0843'),
        ('base', '0062_appconfig_assinatura_nome'),
    ]

    operations = [
    ]
