# Generated by Django 2.2.28 on 2026-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_merge_20260210_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='revisao_setor_legislativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Habilitar etapa de revisão pelo Setor Legislativo?'),
        ),
    ]
