# Generated by Django 2.2.28 on 2026-05-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_appconfig_revisao_setor_legislativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='permite_remover_assinatura',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, help_text='Quando habilitado, superusuários e usuários com a permissão "Pode remover assinatura digital" poderão remover assinaturas de matérias e documentos acessórios para permitir edições.', verbose_name='Permitir remoção de assinatura digital?'),
        ),
    ]
