# Generated by Django 2.2.28 on 2026-02-11 18:43

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materia', '0089_aumenta_justificativa_devolucao_750'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorio',
            name='assinado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Assinatura'),
        ),
        migrations.AddField(
            model_name='documentoacessorio',
            name='assinado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docacessorios_assinados', to=settings.AUTH_USER_MODEL, verbose_name='Assinado por'),
        ),
        migrations.AddField(
            model_name='documentoacessorio',
            name='assinatura_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Metadados do certificado digital usado na assinatura', null=True, verbose_name='Informações da Assinatura'),
        ),
        migrations.AddField(
            model_name='documentoacessorio',
            name='pdf_assinado',
            field=models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.materia.models.anexo_upload_path, verbose_name='PDF Assinado'),
        ),
    ]
