# Generated by Django 2.2.28 on 2026-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0090_add_assinatura_digital_documentoacessorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorio',
            name='codigo_autenticacao',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='Código de Autenticação'),
        ),
        migrations.AddField(
            model_name='materialegislativa',
            name='codigo_autenticacao',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='Código de Autenticação'),
        ),
    ]
