# Generated by Django 2.2.28 on 2026-02-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materia', '0091_add_codigo_autenticacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposicao',
            options={'ordering': ['-data_recebimento'], 'permissions': (('detail_proposicao_enviada', 'Pode acessar detalhes de uma proposição enviada.'), ('detail_proposicao_devolvida', 'Pode acessar detalhes de uma proposição devolvida.'), ('detail_proposicao_incorporada', 'Pode acessar detalhes de uma proposição incorporada.'), ('detail_proposicao_em_revisao_setor', 'Pode acessar detalhes de uma proposição em revisão pelo setor.')), 'verbose_name': 'Proposição', 'verbose_name_plural': 'Proposições'},
        ),
        migrations.AddField(
            model_name='proposicao',
            name='data_envio_setor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio ao Setor Legislativo'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='data_retorno_setor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Retorno do Setor Legislativo'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='observacao_setor',
            field=models.TextField(blank=True, default='', verbose_name='Observação do Setor Legislativo'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='usuario_envio_setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposicoes_enviadas_setor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável pelo Envio ao Setor'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='usuario_retorno_setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposicoes_retornadas_setor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável pelo Retorno do Setor'),
        ),
        migrations.AlterField(
            model_name='historicoproposicao',
            name='status',
            field=models.CharField(choices=[('E', 'Enviada'), ('R', 'Recebida'), ('T', 'Retornada'), ('D', 'Devolvida'), ('S', 'Enviada ao Setor Legislativo'), ('V', 'Revisada pelo Setor Legislativo')], db_index=True, max_length=1, verbose_name='Status de Proposição'),
        ),
    ]
