# Generated by Django 2.2.28 on 2026-05-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_appconfig_revisao_setor_legislativo'),
        ('materia', '0094_add_anexoproposicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoriaProposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_autor', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Primeiro Autor')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Autor', verbose_name='Co-autor')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coautores', to='materia.Proposicao', verbose_name='Proposição')),
            ],
            options={
                'verbose_name': 'Co-autoria da Proposição',
                'verbose_name_plural': 'Co-autorias da Proposição',
                'ordering': ('-primeiro_autor', 'autor__nome'),
                'unique_together': {('proposicao', 'autor')},
            },
        ),
    ]
