# Generated by Django 2.2.28 on 2026-05-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0095_add_autoria_proposicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoacessorio',
            options={'ordering': ('data', 'id'), 'permissions': (('can_remove_assinatura_doc', 'Pode remover assinatura digital de documento acessório'),), 'verbose_name': 'Documento Acessório', 'verbose_name_plural': 'Documentos Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='materialegislativa',
            options={'ordering': ['-ano', 'tipo', 'numero'], 'permissions': (('can_access_impressos', 'Can access impressos'), ('can_remove_assinatura', 'Pode remover assinatura digital')), 'verbose_name': 'Matéria Legislativa', 'verbose_name_plural': 'Matérias Legislativas'},
        ),
    ]
