version: '3.7'

services:
  sapldb-dev:
    container_name: sapldb-dev
    image: postgres:10.5-alpine
    environment:
      POSTGRES_PASSWORD: sapl
      POSTGRES_USER: sapl
      POSTGRES_DB: sapl
    ports:
      - "5435:5432"
    networks:
      - sapl-net-dev

  sapl-dev:
    container_name: sapl-dev
    image: sapl:dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    command: python3 manage.py runserver 0:8000
    volumes:
      - ..:/sapl-dev
    ports:
      - "8002:8000"
    environment:
      SECRET_KEY: '$dkhxm-$zvxdox$g2-&w^1i!_z1juq0xwox6e3#gy6w_88!3t^'
      DJANGO_DEBUG: 'True'
      DATABASE_URL: postgresql://sapl:sapl@sapldb-dev:5432/sapl
      TZ: America/Sao_Paulo
      ONLYOFFICE_URL: 'https://onlyoffice.legisinc.com.br'
      ONLYOFFICE_JWT_ENABLED: 'True'
      ONLYOFFICE_JWT_SECRET: 'sapl_onlyoffice_super_secret'
    networks:
      - sapl-net-dev

networks:
  sapl-net-dev:
    name: sapl-net-dev
    driver: bridge