# Generated by Django 2.2.28 on 2026-08-18 14:13

from django.db import migrations, models
import django.db.models.deletion
import sapl.integracao_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0094_add_anexoproposicao'),
        ('integracao_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoProposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=sapl.integracao_hub.models._caminho_anexo, verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original')),
                ('mime', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('tamanho_bytes', models.BigIntegerField(verbose_name='Tamanho (bytes)')),
                ('hash_sha256', models.CharField(max_length=64, verbose_name='SHA-256 dos bytes recebidos')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anexos_do_app', to='materia.Proposicao', verbose_name='Proposição')),
            ],
            options={
                'verbose_name': 'Anexo de Proposição (app)',
                'verbose_name_plural': 'Anexos de Proposição (app)',
            },
        ),
    ]
