# Generated by Django 2.2.28 on 2026-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracao_hub', '0003_assinaturarecebida_documentoparaassinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturarecebida',
            name='operado_por',
            field=models.CharField(blank=True, help_text='Rastro operacional: quem DISPAROU o ato (o próprio vereador ou um assessor agindo por ele). NÃO é a autoria jurídica — o signatário é sempre o vereador titular (assinatura é ato pessoal e indelegável). Hoje o evento do app ainda não carrega a identidade do assessor logado; até lá recebe o próprio titular.', max_length=150, verbose_name='Operado por'),
        ),
    ]
